[package]
name = "biblio_json"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
itertools = "0.14.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
toml = "0.9.5"
