name = "Standard Strongs Definitions"
short_name = "Strongs Definitions"
id = "standard_strongs_definitions"
license = "Public Domain"
data_source = "Extracted from the SWORD project's StrongsGreek and StrongsHebrew concordances"
language = "en"