use std::str::FromStr;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum OsisBook {
    Gen,
    Exod,
    Lev,
    Num,
    Deut,
    Josh,
    Judg,
    Ruth,
    #[serde(rename = "1Sam")]
    Sam1,
    #[serde(rename = "2Sam")]
    Sam2,
    #[serde(rename = "1Kgs")]
    Kgs1,
    #[serde(rename = "2Kgs")]
    Kgs2,
    #[serde(rename = "1Chr")]
    Chr1,
    #[serde(rename = "2Chr")]
    Chr2,
    Ezra,
    Neh,
    Esth,
    Job,
    Ps,
    Prov,
    Eccl,
    Song,
    Isa,
    Jer,
    Lam,
    Ezek,
    Dan,
    Hos,
    Joel,
    Amos,
    Obad,
    Jonah,
    Mic,
    Nah,
    Hab,
    Zeph,
    Hag,
    Zech,
    Mal,
    Matt,
    Mark,
    Luke,
    John,
    Acts,
    Rom,
    #[serde(rename = "1Cor")]
    Cor1,
    #[serde(rename = "2Cor")]
    Cor2,
    Gal,
    Eph,
    Phil,
    Col,
    #[serde(rename = "1Thess")]
    Thess1,
    #[serde(rename = "2Thess")]
    Thess2,
    #[serde(rename = "1Tim")]
    Tim1,
    #[serde(rename = "2Tim")]
    Tim2,
    Titus,
    Phlm,
    Heb,
    Jas,
    #[serde(rename = "1Pet")]
    Pet1,
    #[serde(rename = "2Pet")]
    Pet2,
    #[serde(rename = "1John")]
    John1,
    #[serde(rename = "2John")]
    John2,
    #[serde(rename = "3John")]
    John3,
    Jude,
    Rev,
}

impl std::fmt::Display for OsisBook {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            OsisBook::Gen => "Gen",
            OsisBook::Exod => "Exod",
            OsisBook::Lev => "Lev",
            OsisBook::Num => "Num",
            OsisBook::Deut => "Deut",
            OsisBook::Josh => "Josh",
            OsisBook::Judg => "Judg",
            OsisBook::Ruth => "Ruth",
            OsisBook::Sam1 => "1Sam",
            OsisBook::Sam2 => "2Sam",
            OsisBook::Kgs1 => "1Kgs",
            OsisBook::Kgs2 => "2Kgs",
            OsisBook::Chr1 => "1Chr",
            OsisBook::Chr2 => "2Chr",
            OsisBook::Ezra => "Ezra",
            OsisBook::Neh => "Neh",
            OsisBook::Esth => "Esth",
            OsisBook::Job => "Job",
            OsisBook::Ps => "Ps",
            OsisBook::Prov => "Prov",
            OsisBook::Eccl => "Eccl",
            OsisBook::Song => "Song",
            OsisBook::Isa => "Isa",
            OsisBook::Jer => "Jer",
            OsisBook::Lam => "Lam",
            OsisBook::Ezek => "Ezek",
            OsisBook::Dan => "Dan",
            OsisBook::Hos => "Hos",
            OsisBook::Joel => "Joel",
            OsisBook::Amos => "Amos",
            OsisBook::Obad => "Obad",
            OsisBook::Jonah => "Jonah",
            OsisBook::Mic => "Mic",
            OsisBook::Nah => "Nah",
            OsisBook::Hab => "Hab",
            OsisBook::Zeph => "Zeph",
            OsisBook::Hag => "Hag",
            OsisBook::Zech => "Zech",
            OsisBook::Mal => "Mal",
            OsisBook::Matt => "Matt",
            OsisBook::Mark => "Mark",
            OsisBook::Luke => "Luke",
            OsisBook::John => "John",
            OsisBook::Acts => "Acts",
            OsisBook::Rom => "Rom",
            OsisBook::Cor1 => "1Cor",
            OsisBook::Cor2 => "2Cor",
            OsisBook::Gal => "Gal",
            OsisBook::Eph => "Eph",
            OsisBook::Phil => "Phil",
            OsisBook::Col => "Col",
            OsisBook::Thess1 => "1Thess",
            OsisBook::Thess2 => "2Thess",
            OsisBook::Tim1 => "1Tim",
            OsisBook::Tim2 => "2Tim",
            OsisBook::Titus => "Titus",
            OsisBook::Phlm => "Phlm",
            OsisBook::Heb => "Heb",
            OsisBook::Jas => "Jas",
            OsisBook::Pet1 => "1Pet",
            OsisBook::Pet2 => "2Pet",
            OsisBook::John1 => "1John",
            OsisBook::John2 => "2John",
            OsisBook::John3 => "3John",
            OsisBook::Jude => "Jude",
            OsisBook::Rev => "Rev",
        };
        write!(f, "{}", s)
    }
}

impl FromStr for OsisBook 
{
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Gen" => Ok(OsisBook::Gen),
            "Exod" => Ok(OsisBook::Exod),
            "Lev" => Ok(OsisBook::Lev),
            "Num" => Ok(OsisBook::Num),
            "Deut" => Ok(OsisBook::Deut),
            "Josh" => Ok(OsisBook::Josh),
            "Judg" => Ok(OsisBook::Judg),
            "Ruth" => Ok(OsisBook::Ruth),
            "1Sam" => Ok(OsisBook::Sam1),
            "2Sam" => Ok(OsisBook::Sam2),
            "1Kgs" => Ok(OsisBook::Kgs1),
            "2Kgs" => Ok(OsisBook::Kgs2),
            "1Chr" => Ok(OsisBook::Chr1),
            "2Chr" => Ok(OsisBook::Chr2),
            "Ezra" => Ok(OsisBook::Ezra),
            "Neh" => Ok(OsisBook::Neh),
            "Esth" => Ok(OsisBook::Esth),
            "Job" => Ok(OsisBook::Job),
            "Ps" => Ok(OsisBook::Ps),
            "Prov" => Ok(OsisBook::Prov),
            "Eccl" => Ok(OsisBook::Eccl),
            "Song" => Ok(OsisBook::Song),
            "Isa" => Ok(OsisBook::Isa),
            "Jer" => Ok(OsisBook::Jer),
            "Lam" => Ok(OsisBook::Lam),
            "Ezek" => Ok(OsisBook::Ezek),
            "Dan" => Ok(OsisBook::Dan),
            "Hos" => Ok(OsisBook::Hos),
            "Joel" => Ok(OsisBook::Joel),
            "Amos" => Ok(OsisBook::Amos),
            "Obad" => Ok(OsisBook::Obad),
            "Jonah" => Ok(OsisBook::Jonah),
            "Mic" => Ok(OsisBook::Mic),
            "Nah" => Ok(OsisBook::Nah),
            "Hab" => Ok(OsisBook::Hab),
            "Zeph" => Ok(OsisBook::Zeph),
            "Hag" => Ok(OsisBook::Hag),
            "Zech" => Ok(OsisBook::Zech),
            "Mal" => Ok(OsisBook::Mal),
            "Matt" => Ok(OsisBook::Matt),
            "Mark" => Ok(OsisBook::Mark),
            "Luke" => Ok(OsisBook::Luke),
            "John" => Ok(OsisBook::John),
            "Acts" => Ok(OsisBook::Acts),
            "Rom" => Ok(OsisBook::Rom),
            "1Cor" => Ok(OsisBook::Cor1),
            "2Cor" => Ok(OsisBook::Cor2),
            "Gal" => Ok(OsisBook::Gal),
            "Eph" => Ok(OsisBook::Eph),
            "Phil" => Ok(OsisBook::Phil),
            "Col" => Ok(OsisBook::Col),
            "1Thess" => Ok(OsisBook::Thess1),
            "2Thess" => Ok(OsisBook::Thess2),
            "1Tim" => Ok(OsisBook::Tim1),
            "2Tim" => Ok(OsisBook::Tim2),
            "Titus" => Ok(OsisBook::Titus),
            "Phlm" => Ok(OsisBook::Phlm),
            "Heb" => Ok(OsisBook::Heb),
            "Jas" => Ok(OsisBook::Jas),
            "1Pet" => Ok(OsisBook::Pet1),
            "2Pet" => Ok(OsisBook::Pet2),
            "1John" => Ok(OsisBook::John1),
            "2John" => Ok(OsisBook::John2),
            "3John" => Ok(OsisBook::John3),
            "Jude" => Ok(OsisBook::Jude),
            "Rev" => Ok(OsisBook::Rev),
            _ => Err(format!("Unknown OSIS book: {}", s)),
        }
    }
}