name = "This is a test package"
authors = [ "Nate Craver" ]
license = "We don't need no stinking license"

[module_paths]
bibles = "/bibles/*"
dictionaries = "/dictionaries/*"
xrefs = "/cross_references/*"
strongs_defs = "/strongs/defs/*"
strongs_links = "/strongs/links/*"
commentaries = "/commentaries/*"